name: "Amine Elafifi"
current_role: "Etudiant technicien d'usinage"
experience_years: 1
target_role: "Technicien d'usinage"

job_preferences:
  roles: 

  locations: 
    - Lyon
    - France
    - Nantes
    - Saint Nazaire
  contract_types: 
    - Stage
    - Intérim
    - CDI
  min_salary: 0
  max_salary: 60000

learning_goals: 
  
